version: '2'
services:
  client:
    image: pwrproject/pet-transfer-system-client:latest
    container_name: client
    network_mode: host
    depends_on:
      - api
  api:
    image: pwrproject/pet-transfer-system-api:latest
    container_name: api
    network_mode: host
  auth:
    image: pwrproject/pet-transfer-system-auth:latest
    container_name: auth
    network_mode: host
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
