micronaut:
  application:
    name: pet-transfer-system
  server:
    port: ${SERVICE_PORT:8081}
    cors:
      enabled: true
      configurations:
        web:
          exposedHeaders:
            - Content-Type
            - Authorization
            - '*'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

jackson:
  bean-introspection-module: true

cloudinary:
  cloud:
    name: ${CLOUD_NAME:drkqvtiuz}
  api:
    key: ${API_KEY:878127959754956}
    secret: ${API_SECRET:tOauaQUIBLKO8Ar7FVOcx0A69d8}

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres?ssl=false
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: postgres
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: create-drop